on:
  push:
    branches:
      - main
      - master
      - bugfix/fix-actions-add-renv
    tags:
      - '*'

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies for stringi
        run: |
          sudo apt-get update
          sudo apt-get install -y libicu-dev

      - name: Restore packages using renv
        run: |
          if (file.exists("renv.lock")) {
            message("Found renv.lock; restoring packages with rebuild of stringi")
            renv::restore(rebuild = "stringi")
          } else {
            message("No renv.lock found; installing dependencies via remotes")
            remotes::install_deps(dependencies = TRUE)
          }
        shell: Rscript {0}

      - name: Cache renv library
        uses: actions/cache@v3
        with:
          path: renv/library
          key: ${{ runner.os }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install package
        run: R CMD INSTALL .

      - name: Build and deploy pkgdown site
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
