on:
  push:
    branches:
      - main
      - master
      - bugfix/fix-actions-add-renv
  pull_request:
    branches:
      - main
      - master
      - bugfix/fix-actions-add-renv
name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libicu-dev
          echo "STRINGI_DISABLE_ICU_BUNDLE=1" >> $GITHUB_ENV

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        shell: Rscript {0}
        run: |
          cov <- covr::package_coverage(quiet = FALSE)
          print(cov) # Print coverage summary to logs
          covr::to_cobertura(cov, "coverage.xml") # Save as Cobertura XML

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
