on:
  push:
    branches:
      - main
      - master
      - bugfix/fix-actions-add-renv
  pull_request:
    branches:
      - main
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        id: install-r

      - name: Restore packages
        run: |
          if (file.exists("renv.lock")) {
            message("Found renv.lock; restoring packages using renv")
            renv::restore()
          } else {
            message("No renv.lock found; installing dependencies using remotes")
            remotes::install_deps(dependencies = TRUE)
          }
        shell: Rscript {0}

      - name: Install covr
        run: install.packages("covr")
        shell: Rscript {0}

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
